name: Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: MJ_FB_Backend
        run: npm ci

      - name: Run backend tests
        working-directory: MJ_FB_Backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: MJ_FB_Frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: MJ_FB_Frontend
        run: npm test

      - name: Build backend image
        run: docker build -t backend:${{ env.IMAGE_TAG }} MJ_FB_Backend

      - name: Build frontend image
        run: docker build -t frontend:${{ env.IMAGE_TAG }} MJ_FB_Frontend

  publish-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_name }}
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      BACKEND_APP_NAME: ${{ vars.BACKEND_APP_NAME }}
      FRONTEND_APP_NAME: ${{ vars.FRONTEND_APP_NAME }}
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Push images
        run: |
          docker tag backend:${{ env.IMAGE_TAG }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ env.IMAGE_TAG }}
          docker tag frontend:${{ env.IMAGE_TAG }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

      - name: Deploy backend
        uses: azure/container-apps-deploy@v2
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.BACKEND_APP_NAME }}
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ env.IMAGE_TAG }}

      - name: Deploy frontend
        uses: azure/container-apps-deploy@v2
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.FRONTEND_APP_NAME }}
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}
